# This file defines some basic scripts used to setup the FINN environment on the runner

.n2_setup_general:
  before_script:
    - module load lang/Python/3.10.4-GCCcore-11.3.0
    - module load devel/Autoconf/2.71-GCCcore-11.3.0
    - module load lang/Bison/3.8.2-GCCcore-11.3.0
    - module load lang/flex/2.6.4-GCCcore-11.3.0
    - module load compiler/GCC/11.3.0
    - module load lib/pybind11/2.9.2-GCCcore-11.3.0
    - module load devel/Boost/1.79.0-GCC-11.3.0
    - module load lib/fmt/9.1.0-GCCcore-11.3.0
    - ulimit -s unlimited # Increase stack size limit

.n2_setup_xilinx_2022_2:
  before_script:
    - module load fpga
    - module load xilinx/xrt/2.14 # includes Vitis/Vivado 2022.2
    # module load will set PLATFORM_REPO_PATHS to one specific platform, revert to top-level PLATFORM_PATH
    - export PLATFORM_REPO_PATHS=$PLATFORM_PATH

.n2_setup_xilinx_2024_2:
  before_script:
    - module load fpga
    - module load xilinx/xrt/2.14 # includes Vitis/Vivado 2022.2
    - module swap xilinx/vitis/24.2 # switch to Vitis/Vivado 2024.2
    # module load will set PLATFORM_REPO_PATHS to one specific platform, revert to top-level PLATFORM_PATH
    - export PLATFORM_REPO_PATHS=$PLATFORM_PATH

.setup_venv_from_whl:
  before_script:
    # Move everything to working directory (e.g., RAMdisk)
    - cp -dfR .. $PATH_WORKDIR
    - cd $PATH_WORKDIR
    # Create fresh virtual environment and install finn-plus from .whl (artifact)
    - python3 -m venv finn-plus-venv
    - finn-plus-venv/bin/pip install ./finn-plus/dist/*.whl

.setup_full_2022_2:
  before_script:
    - !reference [.n2_setup_general, before_script]
    - !reference [.n2_setup_xilinx_2022_2, before_script]
    - !reference [.setup_venv_from_whl, before_script]

.setup_full_2024_2:
  before_script:
    - !reference [.n2_setup_general, before_script]
    - !reference [.n2_setup_xilinx_2024_2, before_script]
    - !reference [.setup_venv_from_whl, before_script]
