params:
  dut: ras
  model_name: MobileNetv2-w8a8_QAT
  validation_dataset: imagenet
  act_mode: standalone
  use_float: yes
  acc_opt: yesaccmin
  folding: prefold
  board: U280
  clock_period_ns: 5
  fifo_method: manual
  enable_instrumentation: false
  top1: no
  rtlsim_n: 5
  output_products:
  - estimate_reports
  - stitched_ip
metadata:
  tool_version: '2022.2'
