params:
  dut: transformer
  seed: 12
  calibration_passes: 32
  model_num_heads: 1
  model_num_layers: 1
  model_bias: true
  model_emb_dim: 32
  model_mlp_dim: 192
  model_seq_len: 64
  model_bits: 2
  model_norm: none
  model_mask: none
  model_positional_encoding: binary
  board: RFSoC2x2
  synth_clk_period_ns: 10
  generate_outputs:
  - estimate_reports
  - bitfile
  - pynq_driver
  - deployment_package
  shell_flow_type: vivado_zynq
metadata:
  tool_version: '2022.2'
