params:
  dut: ras
  model_name: MobileNetv1-w4a4
  act_mode: thresholding
  acc_opt: yesaccmin
  folding: prefold
  board: RFSoC2x2
  clock_period_ns: 5
  fifo_method: manual
  fifo_offset: 256
  rtlsim_n: 5
  output_products:
  - estimate_reports
  - bitfile
  - pynq_driver
  - deployment_package
  target_fps: None
  folding_path: /pc2/groups/hpc-prf-ekiapp/felix/ci_cfg/lfs/CI_88986/folding/CI_88986_7.json
metadata:
  tool_version: '2024.2'
