params:
  dut: ras
  model_name: FINN-CNV_W2A2
  validation_dataset: cifar10
  act_mode: standalone
  use_float: no
  acc_opt: yesaccmin
  folding: prefold
  board: RFSoC2x2
  clock_period_ns: 5
  fifo_method: manual
  enable_instrumentation: false
  top1: no
  rtlsim_n: 5
  output_products:
  - estimate_reports
  - bitfile
  - pynq_driver
  - deployment_package
metadata:
  tool_version: '2022.2'
