params:
  dut: kws
  auto_fifo_depths: true
  auto_fifo_strategy: largefifo_rtlsim
  fifosim_input_throttle: true
  fifosim_n_inferences: 2
  generate_outputs:
  - bitfile
  - pynq_driver
  - deployment_package
  - estimate_reports
  synth_clk_period_ns: 10
  board: RFSoC2x2
  shell_flow_type: vivado_zynq
  model_path: models/kws/MLP_W3A3_python_speech_features_pre-processing_QONNX_opset-11.onnx
metadata:
  tool_version: '2024.2'
