params:
  dut: ras
  model_name: FINN-TFC_W2A2
  validation_dataset: mnist
  act_mode: standalone
  use_float: no
  acc_opt: noaccmin
  folding: prefold
  board: RFSoC2x2
  clock_period_ns: 5
  fifo_method: manual
  enable_instrumentation: false
  rtlsim_n: 5
  output_products:
  - estimate_reports
  - bitfile
  - pynq_driver
  - deployment_package
metadata:
  tool_version: '2022.2'
