params:
  dut: synthetic_nonlinear
  dim: 64
  kernel_size: 5
  ch: 8
  simd: 1
  pe: 1
  parallel_window: 0
  lb_num_layers: 1
  rb_num_layers: 4
  board: RFSoC2x2
  clock_period_ns: 10
  rtlsim_n: 5
  fifo_method: live
  output_products:
  - bitfile
  - pynq_driver
  - deployment_package
metadata:
  tool_version: '2022.2'
