params:
  dut: ras
  model_name: MobileNetv1-w4a4
  act_mode: thresholding
  acc_opt: noaccmin
  folding: autofold
  board: RFSoC2x2
  clock_period_ns: 5
  fifo_method: live
  rtlsim_n: 5
  output_products:
  - estimate_reports
  - stitched_ip
  - bitfile
  - pynq_driver
  - deployment_package
metadata:
  tool_version: '2024.2'
