params:
  dut: transformer
  seed: 12
  model_dir: /pc2/groups/hpc-prf-ekiapp/felix/ci_models/radioml_0
  board: RFSoC2x2
  synth_clk_period_ns: 10
  generate_outputs:
  - estimate_reports
  - bitfile
  - pynq_driver
  - deployment_package
  shell_flow_type: vivado_zynq
metadata:
  tool_version: '2022.2'
