params:
  dut: metafi
  model_path: /pc2/groups/hpc-prf-ekiapp/felix/ci_models/metafi/model.onnx
  folding_config_file: 
    /pc2/groups/hpc-prf-ekiapp/felix/ci_models/metafi/auto_folding_config_metaFi_f25.json
  board: RFSoC2x2
  synth_clk_period_ns: 10
  live_fifo_sizing: true
  generate_outputs:
  - bitfile
  - pynq_driver
  - deployment_package
  shell_flow_type: vivado_zynq
metadata:
  tool_version: '2022.2'
