params:
  dut: ras
  model_name: RN8-CIFAR100_W3A3_pcfpscale
  validation_dataset: cifar100
  act_mode: standalone
  use_float: yes
  acc_opt: yesaccmin
  folding: prefold
  board: RFSoC2x2
  clock_period_ns: 5
  fifo_method: manual
  enable_instrumentation: false
  rtlsim_n: 5
  output_products:
  - estimate_reports
  - bitfile
  - pynq_driver
  - deployment_package
metadata:
  tool_version: '2022.2'
