stages:
  - build
  - measure
  - collect

variables:
  BENCH_CFG:
    description: "Select config, usually provided by parent pipeline"
    value: ""

workflow:
  name: "bench_$BENCH_CFG"

FINN Build:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: build
  needs:
    - job: Fetch Repos
      pipeline: $PARENT_PIPELINE_ID
  variables:
    SCHEDULER_PARAMETERS: "-A $PROJECT_ACCOUNT -p $SLURM_PARTITION -t $SLURM_TIMEOUT $SLURM_QOS --nodes 1 --ntasks 1 --cpus-per-task $CPU_CORES_BENCH --exclusive --array 0-$( expr $PARALLEL_JOBS - 1 )"
    NUM_DEFAULT_WORKERS: "$CPU_CORES_BENCH"
    PYTEST_PARALLEL: "$CPU_CORES_BENCH"
  before_script:
    - cp -dfR .. $PATH_WORKDIR # Copy to working directory (e.g. RAMdisk)
    - cd $PATH_WORKDIR/finn-plus
    # Clone additional DUT repo
    - module load tools/git-lfs/3.5.1
    - git lfs install
    - rm -rf benchmarking/dut/rastreamlining-fpl25
    - git clone -b end2end_ci git@github.com:maltanar/rastreamlining-fpl25.git benchmarking/dut/rastreamlining-fpl25
    - module load system singularity
    - ulimit -s unlimited # Increase stack size limit
    - export FINN_SINGULARITY=$PATH_SINGULARITY_IMG/finn-plus/$SINGULARITY_IMG_SELECT
  script:
    - ./run-docker.sh python benchmarking/bench.py $BENCH_CFG
  cache:
    key: $CI_COMMIT_SHA
    policy: pull
    paths:
      - deps
  artifacts:
    name: "build_artifacts"
    when: always
    paths:
      - build_artifacts/

Measurement:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: measure
  tags:
    - board
  rules:
    # Also run on failure of previous tasks to measure partial results
    - when: always
  script:
    # Run as root and activate the PYNQ venv manually to use PYNQ outside of the typical Jupyter environment
    - sudo bash -c "source /etc/profile.d/pynq_venv.sh && export XILINX_XRT=/usr && python benchmarking/measure.py"
  artifacts:
    name: "measurement_artifacts"
    when: always
    paths:
      - measurement_artifacts/

Result Collection:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: collect
  tags:
    - image_build
  rules:
    # Also run on failure of previous tasks to collect partial results
    - when: always
  script:
    - python3.10 benchmarking/collect.py
    - dvc exp push -f -j 4 -r push git@github.com:eki-project/finn-plus.git
