include: ci/.gitlab-setup.yml

stages:
  - build
  - measure
  - collect

variables:
  BENCH_CFG:
    description: "Select config, usually provided by parent pipeline"
    value: ""

workflow:
  name: "bench_$BENCH_CFG"

Measurement:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: measure
  tags:
    - board
  rules:
    # Also run on failure of previous tasks to measure partial results
    - when: always
  script:
    # Build power measurement driver (TODO: support other boards)
    - make -C ci/power_measurement/boards/rfsoc2x2 shared
    # Run as root and activate the PYNQ venv manually to use PYNQ outside of the typical Jupyter environment
    - sudo bash -c "source /etc/profile.d/pynq_venv.sh && export XILINX_XRT=/usr && python ci/measure.py
  artifacts:
    name: "measurement_artifacts"
    when: always
    paths:
      - measurement_artifacts/

Result Collection:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: collect
  tags:
    - image_build
  rules:
    # Also run on failure of previous tasks to collect partial results
    - when: always
  script:
    # pulling models seems to be needed for dvclive to save experiments, even though they are not used or modified
    - dvc pull
    - python3.10 ci/collect.py
    - dvc exp push -f -j 4 -r push git@github.com:eki-project/finn-plus.git
