# This file defines some basic scripts used to setup the FINN environment on the runner

.n2_setup_general:
  before_script:
    - ml compiler/GCCcore/14.2.0 compiler/GCC/14.2.0 devel/Boost/1.88.0-GCC-14.2.0
    - ml fpga xilinx/xrt/2.14
    - module swap xilinx/u280 xilinx/u55c
    - ml fpga/xilinx/vitis_hls_xcd_fix
    - ulimit -s unlimited # Increase stack size limit

.n2_setup_xilinx_2022_2:
  before_script:
    - module load fpga
    - module load xilinx/xrt/2.14 # includes Vitis/Vivado 2022.2
    # module load will set PLATFORM_REPO_PATHS to one specific platform, revert to top-level PLATFORM_PATH
    - export PLATFORM_REPO_PATHS=$PLATFORM_PATH

.n2_setup_xilinx_2024_2:
  before_script:
    - module load fpga
    - module load xilinx/xrt/2.14 # includes Vitis/Vivado 2022.2
    - module swap xilinx/vitis/24.2 # switch to Vitis/Vivado 2024.2
    # module load will set PLATFORM_REPO_PATHS to one specific platform, revert to top-level PLATFORM_PATH
    - export PLATFORM_REPO_PATHS=$PLATFORM_PATH

.setup_venv_from_whl:
  before_script:
    # Move everything to working directory (e.g., RAMdisk)
    - cp -dfR . $PATH_WORKDIR
    - cd $PATH_WORKDIR
    # Create fresh virtual environment and install finn-plus from .whl (artifact)
    - python3 -m venv finn-plus-venv
    - finn-plus-venv/bin/pip install 'torch~=2.7.1' 'torchvision~=0.22.1' --extra-index-url https://download.pytorch.org/whl/cu121
    - finn-plus-venv/bin/pip install 'dvc[webdav]~=3.59.1' 'dvclive[image]~=3.48.2'
    - finn-plus-venv/bin/pip install tests/dist/*.whl
    - finn-plus-venv/bin/pip install notebooks/dist/*.whl
    - finn-plus-venv/bin/pip install dist/*.whl

.setup_full_2022_2:
  before_script:
    - !reference [.n2_setup_general, before_script]
    - !reference [.n2_setup_xilinx_2022_2, before_script]
    - !reference [.setup_venv_from_whl, before_script]

.setup_full_2024_2:
  before_script:
    - !reference [.n2_setup_general, before_script]
    - !reference [.n2_setup_xilinx_2024_2, before_script]
    - !reference [.setup_venv_from_whl, before_script]
