# Copyright (C) 2020, Xilinx, Inc.
# Copyright (C) 2024, Advanced Micro Devices, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of FINN nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

"""Transformations for inserting and setting the size of FIFOs in FINN dataflow graphs."""

import json
from onnx import NodeProto
from pathlib import Path
from qonnx.core.modelwrapper import ModelWrapper
from qonnx.custom_op.registry import getCustomOp
from qonnx.transformation.base import Transformation
from qonnx.transformation.general import GiveReadableTensorNames, GiveUniqueNodeNames
from typing import TypeAlias, cast

from finn.builder.build_dataflow_config import DataflowBuildConfig
from finn.transformation.fpgadataflow.insert_fifo import InsertFIFO
from finn.transformation.fpgadataflow.specialize_layers import SpecializeLayers
from finn.util.basic import getHWCustomOp
from finn.util.exception import FINNInternalError, FINNUserError
from finn.util.logging import log

FIFODepthConfig: TypeAlias = list[dict[str, list[int]]]


class ApplyFIFODepthsFromFile(Transformation):
    """Apply FIFO depths from a JSON file generated by a previous run of build_dataflow
    with auto_fifo_depths enabled."""

    def __init__(self, fifo_config_file: Path) -> None:
        """Initialize ApplyFIFODepthsFromFile with the path to the FIFO configuration file."""
        super().__init__()
        self.fifo_config_file = fifo_config_file

    def apply(self, model: ModelWrapper) -> tuple[ModelWrapper, bool]:
        """Apply FIFO depths from the configuration file to the model."""
        with self.fifo_config_file.open() as f:
            fifo_info = json.load(f)

        # JSON file format:
        # {
        # "fifo_depths": {
        #     "StreamingFIFO_rtl_0": 2,
        # },
        # "fifo_sizes": {
        #     "StreamingFIFO_rtl_0": 64,
        # },
        # "impl_style": {
        #     "StreamingFIFO_rtl_0": "rtl",
        # },
        # "ram_style": {
        #     "StreamingFIFO_rtl_0": "block",
        # },
        # "total_fifo_size_kiB": 31
        # }
        fifo_nodes = model.get_nodes_by_op_type("StreamingFIFO_rtl")

        # The config file may cover more FIFOs than are present in this model: for multi-DNN
        # builds this transformation is applied once per partial-reconfiguration body and once
        # for the top-level model, all sharing a single config file. Every FIFO of the model
        # must be covered though, which is checked in the loop below.
        if len(fifo_nodes) > len(fifo_info["fifo_depths"]):
            raise FINNUserError(
                f"Number of FIFO nodes in the model ({len(fifo_nodes)}) exceeds the number "
                f"of FIFO nodes in the configuration file ({len(fifo_info['fifo_depths'])})"
            )
        graph_modified = False
        for node in fifo_nodes:
            if node.name not in fifo_info["fifo_depths"]:
                raise FINNUserError(f"FIFO node {node.name} not found in configuration file")
            n_inst = getHWCustomOp(node)
            depth = fifo_info["fifo_depths"][node.name]
            old_depth = n_inst.get_nodeattr("depth")
            if depth == old_depth:
                continue
            impl_style = fifo_info["impl_style"][node.name]
            ram_style = fifo_info["ram_style"][node.name]
            n_inst.set_nodeattr("depth", depth)
            n_inst.set_nodeattr("impl_style", impl_style)
            n_inst.set_nodeattr("ram_style", ram_style)

            producer = model.find_producer(node.input[0])
            if producer is not None:
                prod_node = getHWCustomOp(producer)
                out_fifo_depths = cast("list[int]", prod_node.get_nodeattr("outFIFODepths"))
                succ = cast("list[NodeProto]", model.find_direct_successors(producer))
                num_succ = len(succ)
                if len(out_fifo_depths) != num_succ:
                    out_fifo_depths = [0] * num_succ
                for i, s in enumerate(succ):
                    if s.name == node.name:
                        out_fifo_depths[i] = depth
                prod_node.set_nodeattr(
                    "outFIFODepths", cast("list[int|str|float]", out_fifo_depths)
                )

            graph_modified = True
        return (model, graph_modified)


class ApplySimulatedFIFOSizes(Transformation):
    """Apply a FIFO sizing configuration to the model.
    If FIFOs already exist the step is skipped."""

    def __init__(
        self,
        cfg: DataflowBuildConfig,
        fifo_config: Path | None = None,
    ) -> None:
        """If given read the config json from the given path.
        Otherwise check in the output directory.
        """
        self.cfg = cfg
        self.fifo_config = fifo_config

    def apply(self, model: ModelWrapper) -> tuple[ModelWrapper, bool]:
        """Apply FIFO Simulation Depths to the model."""
        if len(list(filter(lambda node: "StreamingFIFO" in node.op_type, model.graph.node))) > 0:
            log.warning(
                "It seems that StreamingFIFOs have already "
                "been inserted into the graph. Skipping insertion of FIFOs."
            )
            return model, False

        if self.fifo_config is None:
            p = model.get_metadata_prop("fifo_data")
            if p == "" or p is None:
                raise FINNInternalError(
                    "FIFO sizing simulation was not run before inserting simulated FIFO sizes!"
                )
            self.path = Path(p)
        else:
            self.path = self.fifo_config

        self.fifo_depths: FIFODepthConfig = []
        with self.path.open() as f:
            self.fifo_depths = cast("FIFODepthConfig", json.load(f))

        if len(model.graph.node) != len(self.fifo_depths):
            raise FINNUserError(
                "There are no StreamingFIFOs in the graph, yet the number "
                "of nodes and number of FIFO sizes differ. There may be "
                "unaccounted for nodes that have not been part of the FIFO "
                "simulation. Consider re-running simulation directly before "
                "applying the FIFO sizes. It might also be that your model "
                "or config is outdated, in which case it is recommended to "
                "re-run the entire flow from start to finish."
            )

        # FIFO sizes are set as the maximum of outFIFODepth and inFIFODepth of the successor node
        # Only set the outFIFODepth, because setting both is redundant as inFIFODepth defaults to 0.
        # Remove all in/outFIFODepths in model for clean slate
        graph = model.graph
        for node in graph.node:
            # Calculate number of real inputs (predecessors + global inputs)
            predecessors = model.find_direct_predecessors(node)
            num_preds = len(predecessors) if predecessors is not None else 0
            global_ins = [inp for inp in node.input if model.get_initializer(inp) is None]
            num_inputs = len(global_ins) + num_preds
            # Number of outputs is equal to number of elements in node.output,
            # because no initializers can be used as outputs
            successors = len(node.output)
            n = getCustomOp(node)
            if n is not None:
                if num_inputs > 0:
                    n.set_nodeattr(
                        "inFIFODepths",
                        cast("list[str | int | float]", [0] * num_inputs),
                    )
                if successors > 0:
                    n.set_nodeattr(
                        "outFIFODepths",
                        cast("list[str | int | float]", [0] * successors),
                    )

        # Set new outFIFODepths according to config
        graph = model.graph
        node_ind = -1
        for first_node in graph.node:
            node_ind += 1
            n0 = getCustomOp(first_node)
            if n0 is None:
                raise FINNInternalError(
                    f"Node {first_node.name} does not have a custom op instance."
                    " This is required for FIFO insertion."
                )
            if first_node.name != self.fifo_depths[node_ind]["node"]:
                raise FINNInternalError(
                    f"Node name {first_node.name} does not match expected name "
                    f"{self.fifo_depths[node_ind]['node']} at index {node_ind}. "
                    "This may be due to a mismatch between the model and the config, "
                    "or due to changes in the model after the simulation was run. "
                    "Consider re-running the entire flow from start to finish."
                )
            fifos = cast("list[str | int | float]", (self.fifo_depths[node_ind]["depths"]))
            n0.set_nodeattr("outFIFODepths", fifos)

        # Insert the FIFOs into the model
        model = model.transform(InsertFIFO(create_shallow_fifos=True))

        model = model.transform(GiveUniqueNodeNames())
        model = model.transform(GiveReadableTensorNames())
        model = model.transform(SpecializeLayers(self.cfg._resolve_fpga_part()))  # noqa
        model = model.transform(GiveUniqueNodeNames())
        model = model.transform(GiveReadableTensorNames())

        # Sanity check to make sure fifos were inserted
        inserted_fifo_count = sum(
            [int("StreamingFIFO" in node.op_type) for node in model.graph.node]
        )
        if inserted_fifo_count == 0:
            raise FINNInternalError(
                "No FIFOs were inserted. This may be due to "
                "wrong network configuration, step order or "
                "a number of other things."
            )
        if inserted_fifo_count < int(0.4 * float(len(model.graph.node))):
            log.warning(
                "The number of inserted FIFOs makes up less than 40%"
                " of the total number of nodes in the model. This could "
                "point to a potential error."
            )

        return model, False
